# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-27 12:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resources', '0016_resourceoption_journaling'),
        ('ipman', '0012_auto_20160816_2325'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectAdminLicense',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resources.Resource')),
                ('cid', models.IntegerField(db_index=True, verbose_name='Client ID.')),
                ('lid', models.IntegerField(db_index=True, verbose_name='License ID.')),
                ('ip_address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ipman.IPAddressGeneric')),
            ],
            options={
                'abstract': False,
            },
            bases=('resources.resource',),
        ),
    ]
