# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-29 09:26
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


def remove_licenses(apps, schema_editor):
    DirectAdminLicense = apps.get_model("licenses", "DirectAdminLicense")
    DirectAdminLicense.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('resources', '0019_auto_20160827_2204'),
        ('licenses', '0002_remove_directadminlicense_ip_address'),
    ]

    operations = [
        migrations.RunPython(remove_licenses),
        migrations.AddField(
            model_name='directadminlicense',
            name='pool',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='directadmin', to='resources.Resource'),
            preserve_default=False,
        ),
    ]
