# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-29 14:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ipman', '0012_auto_20160816_2325'),
        ('licenses', '0004_auto_20160829_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectAdminLicense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.IntegerField(db_index=True, verbose_name='Client ID.')),
                ('lid', models.IntegerField(db_index=True, verbose_name='License ID.')),
                ('assigned_ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipman.IPAddressPoolGeneric')),
            ],
        ),
    ]
