# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-29 14:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0005_directadminlicense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directadminlicense',
            name='assigned_ip',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='directadminlicense', to='ipman.IPAddressPoolGeneric'),
        ),
    ]
