# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-29 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0007_auto_20160829_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='directadminlicense',
            name='status',
            field=models.CharField(choices=[('free', 'Free to use'), ('inuse', 'Used by someone'), ('failed', 'Failed resource'), ('locked', 'Resource is reserved'), ('deleted', 'Resource is marked to delete')], db_index=True, default='free', max_length=25),
        ),
    ]
