# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-24 20:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipman', '0002_ipaddressgeneric'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipaddressgeneric',
            name='beauty',
        ),
    ]
