# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-25 08:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0016_resourceoption_journaling'),
        ('ipman', '0003_remove_ipaddressgeneric_beauty'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPAddressPoolGeneric',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resources.Resource')),
            ],
            options={
                'abstract': False,
            },
            bases=('resources.resource',),
        ),
    ]
