# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-25 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipman', '0004_ipaddresspoolgeneric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipaddressgeneric',
            name='pool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.Resource'),
        ),
    ]
