# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-26 12:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0016_resourceoption_journaling'),
        ('events', '0008_auto_20160507_1824'),
        ('ipman', '0007_auto_20160726_1336'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IPAddressPoolGeneric',
        ),
        migrations.CreateModel(
            name='IPAddressPoolGeneric',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('resources.resource',),
        ),
    ]
