# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-28 18:35
from __future__ import unicode_literals

from django.db import migrations, models

from ipman.models import IPAddressPoolFactory


def migrate_ips(apps, schema_editor):
    IPAddress = apps.get_model("ipman", "IPAddress")

    if not IPAddress.objects.filter().exists():
        return

    pool = IPAddressPoolFactory.from_name("Global pool")

    for old_ip in IPAddress.objects.all():
        new_ip = pool.add_ip(old_ip.address)

        if old_ip.is_used:
            new_ip.use(old_ip.parent)


class Migration(migrations.Migration):
    dependencies = [
        ('ipman', '0008_auto_20160726_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaddressgeneric',
            name='version',
            field=models.IntegerField(db_index=True, default=0, verbose_name='IP address version'),
        ),
        migrations.RunPython(migrate_ips),
    ]
