# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-13 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipman', '0009_ip_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipaddressgeneric',
            name='address',
            field=models.GenericIPAddressField(db_index=True, unique=True, verbose_name='IPv4/v6 address'),
        ),
    ]
