# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-16 20:25
from __future__ import unicode_literals

from django.db import migrations


def removed_old_resources(apps, schema_editor):
    Resource = apps.get_model("resources", "Resource")

    Resource.objects.filter(type__in=['IPAddress',
                                      'IPAddressPool',
                                      'IPAddressRangePool',
                                      'IPNetworkPool',]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('ipman', '0011_ipaddressgeneric_main'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IPAddress',
        ),
        migrations.DeleteModel(
            name='IPAddressPool',
        ),
        migrations.DeleteModel(
            name='IPAddressRangePool',
        ),
        migrations.DeleteModel(
            name='IPNetworkPool',
        ),
        migrations.RunPython(removed_old_resources),
    ]
