# RemiZOffAlex
#
# Description: Структура для анализатора DDoS атаки

DROP TABLE IF EXISTS ip;
CREATE TABLE `ip` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`ip`	NUMERIC NOT NULL UNIQUE
);
DROP TABLE IF EXISTS domains;

CREATE TABLE `domains` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`domain`	TEXT NOT NULL UNIQUE
);

DROP TABLE IF EXISTS logs;
CREATE TABLE `logs` (
	`id`    INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`ip`    INTEGER NOT NULL,
	`domain`    INTEGER NOT NULL,
	`period`    TEXT NOT NULL,
	`count`     INTEGER,
	FOREIGN KEY(ip) REFERENCES ip(id),
	FOREIGN KEY(domain) REFERENCES domains(id)
);
