#! /bin/sh
### BEGIN INIT INFO
# Provides: youtrack
# Required-Start: $local_fs $remote_fs
# Required-Stop: $local_fs $remote_fs
# Default-Start: 2 3 4 5
# Default-Stop: S 0 1 6
# Short-Description: initscript for youtrack
# Description: initscript for youtrack
### END INIT INFO

export HOME=/home/youtrack
export JAVA_HOME="/usr/lib/jvm/jre-1.8.0-openjdk.x86_64"

set -e

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:$JAVA_HOME/bin:/usr/lib/jvm:$JAVA_HOME/bin:$JAVA_HOME/jre/lib/amd64/jli

NAME=youtrack
SCRIPT=/usr/local/$NAME/$NAME.sh

d_start() {
  su youtrack -l -c "$SCRIPT start"
}

d_stop() {
  su youtrack -l -c "$SCRIPT stop"
}

case "$1" in
  start)
    echo "Starting $NAME..."
    d_start
  ;;
  stop)
    echo "Stopping $NAME..."
    d_stop
  ;;
  restart|force-reload)
    echo "Restarting $NAME..."
    d_stop
    d_start
  ;;
  *)
    echo "Usage: sudo /etc/init.d/youtrack {start|stop|restart}" >&2
    exit 1
  ;;
esac

exit 0
