# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-07 15:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20160507_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyevent',
            name='resource',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resources.Resource'),
        ),
    ]
