# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-26 21:55
from __future__ import unicode_literals

from django.db import migrations, models

from events.models import HistoryEvent
from resources.models import Resource


def update_from_resource(apps, schema_editor):
    HistoryEventObj = apps.get_model("events", "HistoryEvent")
    db_alias = schema_editor.connection.alias
    for hevent in HistoryEventObj.objects.using(db_alias).all():
        exists = Resource.objects.filter(pk=hevent.resource_id).exists()
        if exists:
            if hevent.event_type == HistoryEvent.UPDATE and hevent.field_old_value == hevent.field_new_value:
                hevent.delete()
            else:
                hevent.object_id = hevent.resource.id
                hevent.object_type = hevent.resource.type
                hevent.save()
        else:
            hevent.delete()


class Migration(migrations.Migration):
    dependencies = [
        ('events', '0008_auto_20160507_1824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historyevent',
            old_name='type',
            new_name='event_type',
        ),
        migrations.AddField(
            model_name='historyevent',
            name='object_id',
            field=models.IntegerField(db_index=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historyevent',
            name='object_type',
            field=models.CharField(db_index=True, default='', max_length=64),
            preserve_default=False,
        ),
        migrations.RunPython(update_from_resource),
    ]
