# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-16 08:06
from __future__ import unicode_literals

from django.db import migrations

from events.models import HistoryEvent
from ipman.models import IPAddressGeneric


def relink_ips_journal(apps, schema_editor):
    IPAddress = apps.get_model("ipman", "IPAddress")

    if not IPAddress.objects.filter().exists():
        return

    for event in HistoryEvent.objects.filter(object_type='IPAddress'):
        old_ips = IPAddress.objects.filter(pk=event.object_id)
        if len(old_ips) > 0:
            new_ips = IPAddressGeneric.objects.filter(address=old_ips[0].address)
            if len(new_ips) > 0:
                event.object_id = new_ips[0].id
                event.object_type = 'IPAddressGeneric'
                event.save()


class Migration(migrations.Migration):
    dependencies = [
        ('events', '0010_remove_historyevent_resource'),
        ('ipman', '0011_ipaddressgeneric_main'),
    ]

    operations = [
        migrations.RunPython(relink_ips_journal),
    ]
