# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-17 09:17
from __future__ import unicode_literals

from django.db import migrations

from events.models import HistoryEvent


def update_ipevent_object_type(apps, schema_editor):
    HistoryEvent.objects.filter(object_type='IPAddress').update(object_type='IPAddressGeneric')


class Migration(migrations.Migration):
    dependencies = [
        ('events', '0011_relink_ip_journal'),
    ]

    operations = [
        migrations.RunPython(update_ipevent_object_type),
    ]
