# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-27 15:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0016_resourceoption_journaling'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='type',
        ),
    ]
