# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-27 19:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0017_remove_resource_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
