# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-27 19:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0018_auto_20160827_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='content_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
            preserve_default=False,
        ),
    ]
